### ISSUE TITLE
Ability to run workflows on unavailable entities.

### ISSUE THREAD

**Issue by yleclerc** [a33ik/UltimateWorkflowToolkit#1]
Currently, it's not possible to run workflows on Opportunity Products (or Quote Products or Order Products) records.

Same goes for Contract Lines. That would be a great feature.

**Comment by a33ik** [comment]
Actually you can run workflow against Opportunity Products:
![image](https://user-images.githubusercontent.com/11496007/26853057-813cf3dc-4ade-11e7-990e-25cb2cc5a9e9.png)
The other thing that you can't create or update those. Creation of new Opportunity Products/Quote Details/Order Details/Invoice Details will be a part of the next release.

**Comment by yleclerc** [comment]
Yes that is what I meant. You can't create/update those.
![2017-06-06_18-18-06](https://user-images.githubusercontent.com/29152456/26854558-ae8be89c-4ae4-11e7-8e36-9a313b18c96c.jpg)

Good to know it will be in the next release!!!!

**Comment by a33ik** [comment]
Create scenario is implemented.

![image](https://user-images.githubusercontent.com/11496007/26959438-27a5ec68-4c9e-11e7-8760-e943fa8263b5.png)
![image](https://user-images.githubusercontent.com/11496007/26959454-40ac021a-4c9e-11e7-806c-ad0f0cda0f9c.png)
