### ISSUE TITLE
N:N example

### ISSUE THREAD

**Issue by withersdavid** [a33ik/UltimateWorkflowToolkit#11]
I've tried adding an n:n for access teams.  Put the owner and the entity record in teh references and no luck.  Error is not helpful either.  Any way to get a screen shot of this utility being used in a WF?

**Comment by a33ik** [comment]
Hello,
Why don't you want to use "Add to Access Team" action instead?

**Comment by withersdavid** [comment]
:) i feel dumb... but the view you have to choose the Access team has columns I don't:
To use this saved view, you must remove criteria and columns that refer to deleted or non-searchable items. If you contact support, please provide the technical details.  Now the question is which saved view.?

**Comment by a33ik** [comment]
That's not your problem - it's problem of CRM. Here are steps to resolve it:

1. Open CRM -> Settings -> Customization -> Customize the System.
2.  Entities -> Team Template -> Views -> Teams Quick Find View.
3.  Delete name column and add it back, Save and Close view, Publish All Customizations.

After that issue with "Access Team Template" lookup should be resolved.

**Comment by withersdavid** [comment]
![image](https://user-images.githubusercontent.com/8301663/41337034-a875a616-6eb3-11e8-85f5-f8feb3bc9a43.png)
Here's the settings I used that may come in handy for helping others
