### ISSUE TITLE
CRM error with Add User to Record Team

### ISSUE THREAD

**Issue by LeeMather** [a33ik/UltimateWorkflowToolkit#13]
Hi When I try to add to the Team Template in the Add User to Record Team I get the following error 
Microsoft Dynamics 365
To use this saved view, you must remove criteria and columns that refer to deleted or non-searchable items. If you contact support, please provide the technical details.

here is the log file error Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Server was unable to process request.Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
<ActivityId>eac77754-1c8b-4331-89d3-8498424cd35c</ActivityId>
<ErrorCode>-2140991216</ErrorCode>
<ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
<Message>Server was unable to process request.</Message>
<Timestamp>2018-07-13T15:16:41.5594803Z</Timestamp>
<ExceptionRetriable>false</ExceptionRetriable>
<ExceptionSource i:nil="true" />
<InnerFault i:nil="true" />
<OriginalException i:nil="true" />
<TraceText i:nil="true" />
</OrganizationServiceFault>

Thanks

Lee

**Comment by a33ik** [comment]
Hello Lee,
This issue can be resolved using approach similar to following - https://crmtipoftheday.com/747/if-your-view-is-broken/
Thanks,
Andrew
