### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by yleclerc** [a33ik/UltimateWorkflowToolkit#2]
Is it only compatible wirh CRM 8.2 and more?

We use version 8.1 and I can't import the solution.

Thanks!

**Comment by a33ik** [comment]
Hello,
Check attached.
[UltimateWorkflowToolkit_1_1_0_0_target_CRM_8.1_managed.zip](https://github.com/a33ik/UltimateWorkflowToolkit/files/1068738/UltimateWorkflowToolkit_1_1_0_0_target_CRM_8.1_managed.zip)

**Comment by yleclerc** [comment]
Thanks a lot!!! I will give this a try!!!
