### ISSUE TITLE
Need help with Bulk Operations - Update Records

### ISSUE THREAD

**Issue by ArturZielinski** [a33ik/UltimateWorkflowToolkit#20]
How do you actually specify which fields to update and with what value? Maybe I'm being thick but there's no documentation as far as I can tell..

**Comment by a33ik** [comment]
Artur, You're absolutely right that there is no documentation at the moment. I'll work on it but generally speaking there are 2 ways to create create fields used to update child records - either through manual instantiation of "Request Object" - field by field or through "Build Request from Entity" operation that will accept the list fields from source object (with | separator) and map field corresponding to fields in target entity (again plain string with | separator).

**Comment by ArturZielinski** [comment]
Thanks Andrii for your quick reply. Working great now!

Thanks,
Artur

[Twitter]<https://twitter.com/HitachiSolEu>



[LinkedIn]<https://www.linkedin.com/company-beta/3351095/>



[YouTube]<https://www.youtube.com/channel/UCByItN92P7c5Mbc0FL5gB3A>








Artur Zielinski



azielinski@hitachisolutions.com<mailto:azielinski@hitachisolutions.com>



+44 (0)7872986723<tel:+44%20(0)7872986723>



www.hitachi-solutions.co.uk<http://www.hitachi-solutions.co.uk/>





[Hitachi Solutions]<http://www.hitachi-solutions.co.uk/>
