### ISSUE TITLE
Errors: Address containing special characters (#, &)

### ISSUE THREAD

**Issue by KnielsenOB** [a33ik/UltimateWorkflowToolkit#23]
Case #1: Pound Sign in the Address
                Ex. 1000 Mineral Point Ave. #105B, Janesville, WI 53548
                System Throws: UltimateWorkflowToolkit.CoreOperations.System.GeoCodeAddress: System.Net.WebException: The remote server returned an error: (401) Unauthorized.

Case #2: Ampersand sign in the Address
                Ex. 4th & Walnut Streets, Lebanon, PA 17042
                System Throws: UltimateWorkflowToolkit.CoreOperations.System.GeoCodeAddress: System.IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by a33ik** [comment]
Addresses in 1.5.1.0 build
