### ISSUE TITLE
Annotation:Rename File

### ISSUE THREAD

**Issue by yleclerc** [a33ik/UltimateWorkflowToolkit#29]
Annotation:Rename File

Is there anything particular about this workflow? I am trying to rename a file named "test.txt" in a note.

In the configuration, I typed Current File Name = test.txt

When I run the WF against the Note, I get this error:
"File test.txt is not available for current record"

Full log:
Plugin Trace:

[UltimateWorkflowToolkit.CoreOperations: UltimateWorkflowToolkit.CoreOperations.Annotation.RenameFile]
[UWT: Annotation: Rename File]

Value of 'Resulting File Name' attribute equals to test3
Value of 'Record Reference' attribute equals to <SERVERURL>etc=5&id=bdc407a4-5e46-e911-8125-005056b929fd&histKey=539893382&newWindow=true&pagetype=entityrecord
Value of 'Current File Name' attribute equals to test.txt
Value of 'Throw an Exception on Error' attribute equals to True

Error Message:

Unhandled Exception: Microsoft.Xrm.Sdk.InvalidPluginExecutionException: File test.txt is not available for current record

Am I missing something?
![attempt1](https://user-images.githubusercontent.com/29152456/54362239-f55de980-463e-11e9-9039-a2b88e535f98.png)
![attempt2](https://user-images.githubusercontent.com/29152456/54362240-f55de980-463e-11e9-9ab9-a654e432b134.png)

**Comment by AndrewButenko** [comment]
Hello,
Can you please post screenshot of attachment record?

**Comment by yleclerc** [comment]
Sure!
![note](https://user-images.githubusercontent.com/29152456/54365251-e11ceb00-4644-11e9-898b-62c93af0bfee.png)

**Comment by AndrewButenko** [comment]
Now it's more or less clear. To rename file into "Record Reference" you should pass reference url to a parent record. As far as I can see it should be case. It seems that you pass reference to Annotation.

**Comment by yleclerc** [comment]
Thank you very much, it worked!

I updated the "Record Reference" to the case, and that fixed it.
