### ISSUE TITLE
Bulk Update usage quenstion

### ISSUE THREAD

**Issue by sventepe** [a33ik/UltimateWorkflowToolkit#30]
Hi,

I’m trying to use UWT to update all cp_incidentproduct related to an incident (Anfrage). Somehow I can’t figure out, how this is meant to be used. Can you please tell me?
My intention is to update cp_releaseforshipment on all related entities, that have cp_shipmentrequired set to true (FetchXML Filter).
Currently I’m using the following steps in my action:
 
![image](https://user-images.githubusercontent.com/27802644/55635540-3de17080-57c1-11e9-9984-95cd15ec79f9.png)
![image](https://user-images.githubusercontent.com/27802644/55635555-42a62480-57c1-11e9-96be-f408af2fff96.png)
![image](https://user-images.githubusercontent.com/27802644/55635560-46d24200-57c1-11e9-83ef-4eb408d7aacd.png)
![image](https://user-images.githubusercontent.com/27802644/55635567-49cd3280-57c1-11e9-98cf-58de58f55223.png)
 
 
On the 3rd step I get the following error:
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Newtonsoft.Json.JsonReaderException,UltimateWorkflowToolkit.CoreOperations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=47b099d1948ebf4d'. at Microsoft.Crm.Sandbox.SandboxAppDomainHelper.Execute(IOrganizationServiceFactory organizationServiceFactory, String customActivityTypeName, IExecutionContext requestContext, Dictionary`2 sandboxServices, Boolean useDrawbridgeEnabled, Boolean chaosFailAppDomain) at Microsoft.Crm.Sandbox.SandboxWorker.ExecuteCustomWorkflowActivity(SandboxCallInfo callInfo, SandboxCustomActivityExecutionContext requestContext, Guid pluginAssemblyId, Int32 sourceHash, String assemblyName, Guid pluginTypeId, String pluginTypeName, SandboxRequestCounter& workerCounter, Boolean returnTraceInfo): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #BAA05F2C

Thanks you!

Regards

Sven

**Comment by YuriyVoskoboynoiy** [comment]
I guess, you need input your fetchXML as string.

**Comment by AndrewButenko** [comment]
In the third step you should pass "Dynamic Record Url" instead of record name. You can see example here - https://github.com/a33ik/UltimateWorkflowToolkit/wiki/Record-Reference---polymorphic-lookup

Feel free to update your findings here.

**Comment by sventepe** [comment]
Thank you, that did it :)
