### ISSUE TITLE
Get Opportunity Close - multiple opportunity close activities

### ISSUE THREAD

**Issue by stevenfayers** [a33ik/UltimateWorkflowToolkit#37]
If an opportuntity is closed, reopened and closed again there are 2 opportunity close activities. The "Get Opportunity Close" doesn't necessarily always get the last activity record.

**Comment by AndrewButenko** [comment]
Steven,
I have the code that filters-out all "former" closed opportunity close records - https://github.com/AndrewButenko/UltimateWorkflowToolkit/blob/master/CoreOperations/Base/GetResolutionWorkflowBase.cs
When opportunity is reopened all previous opportunityclose records are marked as "canceled", i.e. statecode = 2. It should work normally.
How do you reopen opportunities?
Andrew

**Comment by stevenfayers** [comment]
Hi Andrew

We reopen them with "reopen opportunity" on the ribbon.
Cheers
Steven

**Comment by stevenfayers** [comment]
Just had a look at the 2 closed records, and both have a status of
"Completed"

**Comment by AndrewButenko** [comment]
Steven,
2 records with "Completed" status doesn't look correct for me.
Are you online or on-prem?
Andrew

**Comment by stevenfayers** [comment]
You're right that is doesn't look correct. We're online. I just tested a
fresh record and it's fine. The activities are cancelled. So I need to
search elsewhere why we ended up with the previous record not being
cancelled. Thanks for your quick feedback.
Cheers
Steven

**Comment by AndrewButenko** [comment]
Steven,
I would say - try to open a ticket with Microsoft. They would be able to help you with this issue.
I will close the issue if you don't mind.
Andrew

**Comment by stevenfayers** [comment]
Thanks. I've opened a ticket with MS.
