### ISSUE TITLE
Duplicate Detection Check

### ISSUE THREAD

**Issue by zzecevic** [a33ik/UltimateWorkflowToolkit#39]
Hi, I tried Duplicate Detection Check Action on Account record and got following message: 

An unexpected error occurred from ISV code. (ErrorType = ClientError) Unexpected exception from plug-in (Execute): UltimateWorkflowToolkit.CoreOperations.Common.CheckForDuplicates: System.NullReferenceException: Object reference not set to an instance of an object._

![Capture](https://user-images.githubusercontent.com/62388162/77948998-8cd3c000-72c6-11ea-8e19-bf14e6428ce9.JPG)

![Capture2](https://user-images.githubusercontent.com/62388162/77949195-d2908880-72c6-11ea-8c62-ec43c518eb18.JPG)

What to do next?
Thanks!

Zvjezdana

**Comment by AndrewButenko** [comment]
Hello Zvjezdana,
Can you open solution, navigate to "Solution Configuration Page" and click "Save" and retry workflow to run?
Thanks,
Andrew

**Comment by zzecevic** [comment]
It worked! Thank You Andrew on fast reply.
