### ISSUE TITLE
UWT: DateTime Operations:Format DateTime - How to use "format"?

### ISSUE THREAD

**Issue by Flschw** [a33ik/UltimateWorkflowToolkit#43]
Hi,

I want to use the UWT: DateTime Operations:Format DateTime workflow. When you open properties of this Workflow, you get this view:
![image](https://user-images.githubusercontent.com/63564715/110772503-f80a6e00-825b-11eb-96b6-397ff7a376ef.png)

Currently, I do not know what to insert into format. I want the date (which is a dynamic field variable) to be changed into "31-12-YYYY", which means, that only the year of the dynamic field variable (which is a date field) has to be used, and month and day should always be "31-12".

I tried a view variants in "format", like

- "31.12.yyyy"
- 31-12-yyyy
- 'yyyy/12/31
- etc

but the result was always incorrect.

Can you tell me what is the correct value to be inserted into "format"?

BR

Flo

**Comment by AndrewButenko** [comment]
The explanation why it doesn't work is simple enough - FormatDateTime step, as a result, produces a string, not DateTime and that is why you can use that value to populate the other DateTime field. Also, I don't have the step that parses a string to DateTime.

As a potential workaround you can use the other Custom Workflow Steps toolkit - https://github.com/jlattimer/CRM-DateTime-Workflow-Utilities - it contains "ToDateTime" step that can give you what you need.
