### ISSUE TITLE
Bulk execution of Action

### ISSUE THREAD

**Issue by fvakiliev** [a33ik/UltimateWorkflowToolkit#5]
Hi Andrew!

You have a wonderful workflow step - _Bulk Operations: Distribute Workflow_, but...
It would be very cool to do more - _Bulk Operations: Distribute Action_ !
Very necessary!

Regards,
OldCat

PS: What about the support for D365 v9.0?

**Comment by a33ik** [comment]
Hello,
I have already thought of that step but I'm still not sure what would be the best way to pass additional parameters inside (except Target).
Regarding support - you can import latest version to v9.0 and it should work without any issues.
Thanks,
Andrew

**Comment by a33ik** [comment]
@fvakiliev do you have any idea what would be the best way to pass additional parameters inside action? I think about passing it through Xml or JSon format.
@jlattimer @daryllabar collegues do you have suggestions or ideas?

**Comment by jlattimer** [comment]
Just thinking out loud... your distribute action step would need to take the action name, entity name (if not global), the parameters, and the list of records/query. I'm partial to JSON - so your parameters could be one big JSON string which would need to be deserialized into their actual types as the first step before calling the action. You'd probably need to have a consistent pattern for structuring the JSON so the complex types that can be parameters are sent correctly by the person setting up the workflow. Maybe you create a totally separate custom workflow step which accepts the action name and then it finds the parameters and returns a pre-built JSON string you can use in the distribute step, just needs to be filled in with actual values in the correct places. Or maybe you just don't handle complex types. Not sure how or if you'd even bother trying to handle the action outputs if there were any.

**Comment by daryllabar** [comment]
If I'm dealing with a C# call to a C# call, I use XML.  If there is a chance that is want to call it from JavaScript, I go with JSON...

**Comment by a33ik** [comment]
@fvakiliev implemented in latest release.

**Comment by fvakiliev** [comment]
Hi Andrew!

My attempt to upgrade _UltimateWorkflowToolkit_ from 1.3.0.0 to 1.5.0.0 failed with error: 

> Plug-in assembly does not contain the required types or assembly content cannot be updated.

I think that I'll have to reconsider all my workflows that use the _UltimateWorkflowToolkit_ steps (but there are a lot of them).
What can you advise?

Regards,
OldCat
