### ISSUE TITLE
Duplicate Record Check

### ISSUE THREAD

**Issue by JerryCRMI** [a33ik/UltimateWorkflowToolkit#6]
When a new record is created, run the duplicate check rule(s) for that entity and if there is a match, add a note to the new record that this could be a possible duplicate, with a link to the other duplicate(s) records.

**Comment by a33ik** [comment]
@JerryCRMI code is ready. I'm testing it, planning to release new version of toolkit the next week.
Andrew

**Comment by JerryCRMI** [comment]
Cool



Jerry Weinstock
Business Technology Strategist
CRM Innovation LLC
913 492 2764 x1



-------- Original message --------

**Comment by a33ik** [comment]
@JerryCRMI implemented in latest release.
