### ISSUE TITLE
Can't import v1.4.0.0 to CRM 8.2

### ISSUE THREAD

**Issue by fvakiliev** [a33ik/UltimateWorkflowToolkit#7]
Hi Andrew!

I can't import managed solution v1.4.0.0 to on-premises CRM Org. with API v8.2. I think that this version only for 9.X. Right?

OldCat

**Comment by a33ik** [comment]
Hello,
That's correct. I included functions to work with Multiselect Optionsets only and 1.4 supports 9.0 only.
Andrew
