### ISSUE TITLE
"Lock/Unlock Pricing" on Opportunities and Quotes

### ISSUE THREAD

**Issue by yleclerc** [a33ik/UltimateWorkflowToolkit#8]
Hi Andrii,

Is there a reason you did not implement the "Lock/Unlock Pricing" on Opportunities and Quotes?

Thinking out loud, if you have a product (price list item) for which the price changes often, and you want to lock the prices for opportunities/quotes that already have been sent out to the customer, you need to manually override the price for that product.

Trying to be as clear as possible here...

I add Product A to an opportunity/quote. Price is $100. I submit that price to that customer.

The next day, Price goes up to $150.

If I update the price in CRM, the Opportunity now shows $150. But I submitted $100 to the customer, and I have to stand by that price because it was submitted before the price increase.

I know we can override the price in the Opportunity Product, but this have to be done manually. So if I create 20 quotes a day, which all have 10 products in them, I have to update 200 opportunity products BEFORE the price changes...

Does my explanation make any sense?

**Comment by a33ik** [comment]
Hello,
Your explanation makes sense but answer that I have I believe will not satisfy you. The reason why it was not implemented in toolkit - because it is not implemented in SDK. There are special messages that lock prices for Invoices and Orders but those are absent for Opportunities and Quotes. That is why I haven't added steps to toolkit.
Andrew

**Comment by yleclerc** [comment]
Great, thanks for your timely answer Andrew!

Well, not being a programmer, I have an additional question ☺.

Even if it’s not in the SDK, could we still develop a custom activity workflow to lock the prices?

Thanks again.
