### ISSUE TITLE
What is the UWT Settigs entity?

### ISSUE THREAD

**Issue by fvakiliev** [a33ik/UltimateWorkflowToolkit#9]
Hi Andrew!

What is the **UWT Settigs** entity? For the normal operation of the **UltimateWorkflowToolkit** steps has to give privileges to this entity! Tell me about this in more detail, please.

For example: if I use **UWT: Request Builder:Set Lookup Field** step, and current user have't readAccess to **UWT Settings** - I'll get error:

> Principal user (Id=XXXXXXXX-4151-e111-a222-005056b30006, type=8) is missing prvReaduwt_settings privilege (Id=45156824-f79a-4a21-ba62-d349bbcbb999).

Regards,
OldCat

**Comment by a33ik** [comment]
Hello,
This entity is used to store settings for BingMaps, CloudConvert and Currency service. You can find detailed explanation here - https://github.com/a33ik/UltimateWorkflowToolkit/wiki/Convert-File-(from-attachments)
This is definitely a bug. I will fix it and upload new version.
Thanks,
Andrew

**Comment by a33ik** [comment]
I find out something new today - https://msdn.microsoft.com/en-us/library/microsoft.xrm.sdk.iorganizationservicefactory.createorganizationservice.aspx
Take a look on piece related to 

> Parameters
> userId
> Type: System.Nullable<Guid>
> Type: Nullable<Guid>. Specifies the system user that calls to the service are made for.
> 
> When called in a plug-in, a null value indicates the SYSTEM user and a Guid.Empty value indicates the same user as IPluginExecutionContext. UserId. Any other value indicates a specific system user.
> 
> **When called in a custom workflow activity, all service calls are made in the IWorkflowExecutionContext.UserId context.**

Seems that the only way it will work - you will have to provide user privilege to read that entity.

**Comment by fvakiliev** [comment]
Ok. I'll be add **prvReaduwt_settings** privilege to default security role (for all users).
Thanks!
